core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
]

djangochat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('rooms/', include('room.urls')),
]

room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('rooms/', views.rooms, name='rooms'),
    path('<str:slug>/', views.room_detail, name='detail'),
]

core/models.py
from django.db import models

room/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
    

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login

from .forms import SignUpForm, LoginForm

def frontpage(request):
    return render(request, 'core/frontpage.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect('core:frontpage')
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {'form': form})

room/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Room, Message

@login_required
def rooms(request):
    rooms = Room.objects.all()
    return render(request, 'room/rooms.html', {'rooms': rooms})

@login_required
def room_detail(request, slug):
    room = get_object_or_404(Room, slug=slug)
    messages = Message.objects.filter(room=room)[0:25]
    return render(request, 'room/detail.html', {'room': room, 'messages': messages})

core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Djangochat</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  
    <style>
      .chat-messages {
        height: 400px;
        overflow-y: auto;
      }
    </style>
  </head>
  <body>
    {% include 'core/navbar.html' %}

    <div class="container">
        <br/>
    </div>

    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Front page{% endblock %}

{% block content %}
    frontpage!!!
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div>
    <h1>Log in</h1>
</div>

<div class="container">
    <form method="POST" action=".">
        {% csrf_token %}
        
        <div>
            <label>Username</label>

            <input type="text" name="username" class="w-full rounded-xl">
        </div>
        <div>
            <label>Password</label>

            <input type="text" name="password" class="w-full rounded-xl">
        </div>

        {% if form.errors or form.non_field_errors %}
            {% for field in form %}
                {% for error in field.errros %}
                    <p>{{ error|escape }}</p>
                {% endfor %}
            {% endfor %}

            {{ form.non_field_errors }}
        {% endif %}

        <button class="btn btn-success">Log in</button>
    </form>
</div>
{% endblock %}

core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'core:frontpage' %}">Djangochat</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        </ul>
      </div>
      <div>
        {% if request.user.is_authenticated %}
        <a href="{% url 'room:rooms' %}" class="btn btn-success" type="button">Chat</a>
        <a href="/logout/" class="btn btn-secondary" type="button">Log out</a>  
        {% else %}
        <a href="/login/" class="btn btn-success" type="button">Log in</a>
        <a href="/signup/" class="btn btn-secondary" type="button">Sign up</a>  
        {% endif %}
    </div>
    </div>
  </nav>

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div>
    <h1>Sign up</h1>
</div>

<div class="container">
    <form method="POST" action=".">
        {% csrf_token %}
        
        <div>
            <label>Username</label>

            <input type="text" name="username" class="w-full rounded-xl">
        </div>
        <div>
            <label>Password</label>

            <input type="text" name="password1" class="w-full rounded-xl">
        </div>
        <div>
            <label>Repeat password</label>

            <input type="text" name="password2" class="w-full rounded-xl">
        </div>

        {% if form.errors or form.non_field_errors %}
            {% for field in form %}
                {% for error in field.errros %}
                    <p>{{ error|escape }}</p>
                {% endfor %}
            {% endfor %}

            {{ form.non_field_errors }}
        {% endif %}

        <button class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}

room/templates/room/detail.html
{% extends 'core/base.html' %}

{% block title %}{{room.name}}{% endblock %}

{% block content %}
<h1>{{room.name}}</h1>

<div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-messages">
        {% for message in messages %}
        <div class="p-4 bg-gray-200 rounded-xl">'
            <p>{{ message.user.username }}</p>
            <p>{{ message.content }}</p>
        </div>
        {% endfor %}
    </div>
</div>

<div>
    <form method="POST" action=".">
        
        <input type="text" name="content" placeholder="Your message..." id="chat-message-input">
        <button class="btn btn-success" id="chat-message-submit">Submit</button>

    </form>

</div>
{% endblock %}

{% block scripts %}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);
    
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        console.log('onmessage')

        const data = JSON.parse(e.data);

        if (data.message) {
            let html = '<div class="p-4 bg-gray-200 rounded-xl">';
                html += '<p>' + data.username + '</p>';
                html += '<p>' + data.message + '</p></div>';

            document.querySelector('#chat-messages').innerHTML += html;
        
            scrollToBottom();
        } else {
            alert('The message was empty!');
        }
    }

    chatSocket.onclose = function(e) {
        console.log('onclose')
    }

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault();

        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName
        }))

        messageInputDom.value = '';

        return false;
    }

    function scrollToBottom() {
        const objDiv = document.querySelector('#chat-messages')
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    scrollToBottom();
</script>
{% endblock %}

room/templates/room/rooms.html
{% extends 'core/base.html' %}

{% block title %}Rooms{% endblock %}

{% block content %}
<h1>Rooms</h1>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl"></div>
    <div class="grid grid-cols-3 gap-3">
        {% for room in rooms %}
        <div>
            <a href="#">
                <div>
                    <h3><strong>{{room.name}}</strong></h3>
                </div>
                <div>
                    <a href="{% url 'room:detail' room.slug %}" class="btn btn-success" type="button">Join</a>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}